### ISSUE TITLE
Problem on Python >= 2.7

### ISSUE THREAD

**Issue by iwbh15** [stefanv/supreme#3]
I have tried to setup and install SUPREME on Win10/64bit with Python 2.7 and 3.7.
It seems that SUPREME is not running on this current platforms since Python 2.7 CObjects are deprecated.

Are there any plans or chances that SUPREME will be modified to be able to run on Python 3.7?
Thanks,
Peter

**Comment by stefanv** [comment]
Hi Peter,

Sorry, I missed this earlier. Python 3 should be trivial to support, since we use Cython. Is there any particular feature that you need? A lot of it now lives in scikit-image.
